### ISSUE TITLE
It's invisible

### ISSUE THREAD

**Issue by songproducer** [nocodeco/Bubble-Plugin-Howler.js-music-audio-player#1]
> The plugin Howler.js music / sound player threw the following error: ReferenceError: Howl is not defined
>     at eval (eval at g.create_code (https://dhtiece9044ep.cloudfront.net/package/run_debug_js/855f140f3404fa2ae6b4138baadd016116578eb821f627b014e326e10d3b32e2/xfalse/x3:100:11832), <anonymous>:3:18)
>     at https://dhtiece9044ep.cloudfront.net/package/run_debug_js/855f140f3404fa2ae6b4138baadd016116578eb821f627b014e326e10d3b32e2/xfalse/x3:101:1444
>     at N (https://dhtiece9044ep.cloudfront.net/package/run_debug_js/855f140f3404fa2ae6b4138baadd016116578eb821f627b014e326e10d3b32e2/xfalse/x3:100:25442)

**Comment by songproducer** [comment]
Now the error is not coming up anymore but the main problem is that the visibility is off.

I tried adding a condition to turn the visibility on but it's still off.

It was underneath another element so I brought it to front and managed to get it to be visible in the inspector, but it's still invisible.

ID attribute is empty, not sure if it should be.

**Comment by will-ks** [comment]
It's always invisible, the plugin doesn't have a visible interface. You start and stop playback in the workflows. If you want a visible interface, you can construct one from buttons or whatever you want, that start / stop playback through workflows.

**Comment by songproducer** [comment]
Thanks!!
